
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Load packages from packages folder
homeassistant:
  packages: !include_dir_named packages

# Logging configuration
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.zigbee2mqtt: debug
    custom_components: debug

# HTTP configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# CozyLife Integration
hass_cozylife_local_pull:
  lang: en
  ip:
    - "192.168.100.12"  # Replace with your actual CozyLife device IP addresses

# Include other configuration files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
