services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
    environment:
      - TZ=Europe/Budapest
    privileged: true

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant-config:/config
    environment:
      - TZ=Europe/Budapest

volumes:
  mosquitto_data:
  mosquitto_config:
