services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
    environment:
      - TZ=Europe/Budapest
    privileged: true

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant-config:/config
    environment:
      - TZ=Europe/Budapest

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
    volumes:
      - ./plex-config:/config
      - ./plex-transcode:/transcode
      - /mnt/nas/movies:/movies:ro
    environment:
      - TZ=Europe/Budapest
      - PLEX_CLAIM=claim-w3Kaez4Ry4z3WztQ5ySf
      - PLEX_UID=1000
      - PLEX_GID=1000

volumes:
  mosquitto_data:
  mosquitto_config:
