services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
    environment:
      - TZ=Europe/Budapest
    privileged: true

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant-config:/config
    environment:
      - TZ=Europe/Budapest

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    volumes:
      - ./plex-config:/config
      - ./plex-transcode:/transcode
      - /mnt/nas/movies:/media:ro
    environment:
      - TZ=Europe/Budapest
      - PLEX_CLAIM=claim-V7uLSimxuRnHQxcmYobY
      - PLEX_UID=1000
      - PLEX_GID=1000
      - PLEX_MEDIA_SERVER_DEBUG=true
    network_mode: host
    privileged: true

  adguard-home:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    restart: unless-stopped
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "3000:3000"
      - "3001:3001"
      - "8081:8080"
    volumes:
      - ./adguard-home:/opt/adguardhome/conf
      - ./adguard-home/work:/opt/adguardhome/work
    environment:
      - TZ=Europe/Budapest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

volumes:
  mosquitto_data:
  mosquitto_config:
