services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
    environment:
      - TZ=Europe/Budapest
    privileged: true

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant-config:/config
    environment:
      - TZ=Europe/Budapest

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
    volumes:
      - ./plex-config:/config
      - ./plex-transcode:/transcode
      - /mnt/nas/movies:/movies:ro
    environment:
      - TZ=Europe/Budapest
      - PLEX_CLAIM=claim-w3Kaez4Ry4z3WztQ5ySf
      - PLEX_UID=1000
      - PLEX_GID=1000

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
    volumes:
      - ./wireguard-config:/config
    environment:
      - TZ=Europe/Budapest
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

volumes:
  mosquitto_data:
  mosquitto_config:
