homeassistant:
  enabled: true
frontend:
  enabled: true
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1883
serial:
  port: tcp://192.168.100.2:6638
  adapter: ezsp
advanced:
  log_level: info
  pan_id: 6755
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
devices:
  '0xa4c1382e6175d404':
    friendly_name: '0xa4c1382e6175d404'
  '0xa4c138d674cd6572':
    friendly_name: '0xa4c138d674cd6572'
  '0xa4c138ba59ea2e55':
    friendly_name: '0xa4c138ba59ea2e55'
groups: {}
version: 4
